node {

    withMaven(maven:'maven') {

        stage('Checkout') {
            git url: 'https://github.com/sasi-infy/Azure.git', credentialsId: '5bdf415a-60a4-4b47-9947-f4ce7fdf8812	', branch: 'master'
        }

        stage('MVNBuild') {
            sh 'mvn clean install'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }

        stage('DCKRBuild') {
            dir ('discovery-service') {
                def app = docker.build "localhost:5000/discovery-service:${env.version}"
                app.push()
            }
        }

        stage ('DCKRRun') {
            docker.image("localhost:5000/discovery-service:${env.version}").run('-p 8761:8761 -h discovery --name discovery')
        }

        stage ('Final') {
            build job: 'account-service-pipeline', wait: false
        }      

    }

}
